version: '3.8'

services:
  # Main application service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 911-analytics-app
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./plots:/app/plots
      - ./reports:/app/reports
      - ./logs:/app/logs
    environment:
      - PYTHONPATH=/app/src
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    restart: unless-stopped
    networks:
      - analytics-network
    command: ["streamlit", "run", "dashboard/app.py", "--server.port=8501", "--server.address=0.0.0.0"]

  # PostgreSQL database (for future use)
  postgres:
    image: postgres:13
    container_name: 911-analytics-db
    environment:
      POSTGRES_DB: emergency_calls
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - analytics-network

  # Redis for caching (for future use)
  redis:
    image: redis:6-alpine
    container_name: 911-analytics-cache
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - analytics-network
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  # Nginx reverse proxy (for production)
  nginx:
    image: nginx:alpine
    container_name: 911-analytics-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - analytics-network

networks:
  analytics-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:

# Override for development
---
# docker-compose.override.yml content for development
version: '3.8'

services:
  app:
    build:
      target: development
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - DEBUG=true
      - RELOAD=true
    command: ["streamlit", "run", "dashboard/app.py", "--server.port=8501", "--server.address=0.0.0.0", "--server.runOnSave=true"]

  # Development tools
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 911-analytics-jupyter
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    environment:
      - JUPYTER_ENABLE_LAB=yes
    command: ["jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root", "--NotebookApp.token=''"]
    networks:
      - analytics-network 